### PR TITLE
Correcting and Adding missing things

### PR DESCRIPTION
**Pull request by AaronStra**
Correcting SSC_test,
adding precalculated data,
adding plotting makros

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Hi Aaron, 
we don't need precalculated data, can you remove them? thank you.

**Comment by AaronStra** [comment]
Hi Cosimo,

the plotting makros do only work with this
Data. That's why I left it in. 

Greetings,
Aaron

Am 08.11.17 um 11:10 schrieb Cosimo Nigro

**Comment by cosimoNigro** [comment]
This is what I get cloning your repo and running 
`python SSC_test.py`
Can you please make sure that the macro is working? I am using `python 2.7` like you
fail

**Comment by cosimoNigro** [comment]
Ok let's do like this to spare time: I will find a way myself to merge your changes, for now I am closing this PR since also the merged is blocked, it has conflict that must be resolved.

**Pull request closed without merging**
